@if ($data->booth == 'Booth 3x1')
    @include('frontend.form.form-5.sticker.3x1')
@elseif ($data->booth == 'Booth 3x1 Hook')
    @include('frontend.form.form-5.sticker.3x1-hook')
@elseif ($data->booth == 'Booth 3x2')
    @include('frontend.form.form-5.sticker.3x2')
@elseif ($data->booth == 'Booth 3x2 Hook')
    @include('frontend.form.form-5.sticker.3x2-hook')
@elseif ($data->booth == 'Booth 3x3')
    @include('frontend.form.form-5.sticker.3x3')
@elseif ($data->booth == 'Booth 3x3 Hook')
    @include('frontend.form.form-5.sticker.3x3-hook')
@elseif ($data->booth == 'Booth 5x3')
    @include('frontend.form.form-5.sticker.5x3')
@elseif ($data->booth == 'Booth 6x2')
    @include('frontend.form.form-5.sticker.6x2')
@endif
